spring.application.name=kafkasservice
server.port=8085

spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

# --- Producer ---
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

# --- Consumer ---
spring.kafka.consumer.group-id=productkafkaservice-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer

kafka.topic.productos=modelo-productos-topico
kafka.topic.payments=payments_retry_jobs
kafka.topic.orders=order_retry_jobs
kafka.topic.products=products_retry_jobs

# Datos de conexión
spring.datasource.url=${DATASOURCE_URL:jdbc:postgresql://localhost:5432/failed_products_db}
spring.datasource.username=${DATASOURCE_USERNAME:postgres}
spring.datasource.password=${DATASOURCE_PASSWORD:mysecretpassword}

# Estrategia de actualización de tablas
# 'update' es ideal para desarrollo porque crea la tabla de errores si no existe
spring.jpa.hibernate.ddl-auto=update

# Opcional: Para ver en consola qué está haciendo el Job de reintento
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ── MongoDB ──────────────────────────────────────────────────────────────
spring.data.mongodb.uri=${MONGODB_URI:mongodb://localhost:27017/broker_message_db}
spring.data.mongodb.auto-index-creation=true
spring.mongodb.uri=${MONGODB_URI:mongodb://localhost:27017/broker_message_db}

# ── Mail (SMTP) ──────────────────────────────────────────────────────────
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=renzo.dealbac@gmail.com
spring.mail.password=yuoz rotq lmgp kwtc
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

app.mail.from=renzo.dealbac@gmail.com
app.mail.to=renzo.dealbac@gmail.com

# ── WebClient base URL ──────────────────────────────────────────────────
app.almacen.base-url=http://localhost:8081/api/almacen